### PR TITLE
Added Antarctica (aq) divisions #23

### PR DESCRIPTION
**Pull request by hiwye**
Wow, this is quite a lot of work :P

### CODE REVIEW

**Comment by Omranic** [comment]
Oh, wow! And with lot of work, comes lot of appreciation 😉 
Will review & merge soon 👍

**Comment by hiwye** [comment]
Hopefully I will find some more time to continue with some of the other
countries...
Today this was my first time working with geo coordinates, that might also
be the reason why it took so long. :)


--
Sebastian Walker
Mercystraße 13
79100 Freiburg
Deutschland

walkermedia Webservices
http://sebastianwalker.org

2016-10-02 17:52 GMT+02:00 Abdelrahman Omran <notifications@github.com>:

**Comment by Omranic** [comment]
Cool, I hope you get something out of it as well 😄 
Anyway, to cut down the amount of work required, you may skip the alternative names, it's optional for now.

**Comment by hiwye** [comment]
Well, as I am German it is easy for me to quickly add the German names. Also, I simply copied the alternative names that Wikipedia mentions for the different sectors.

**Pull request merged**
